# Generated by Django 5.2.4 on 2025-08-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_description_review_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
